name: Orka CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install ansible requests
          deactivate

      - name: Install Orka CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sSL https://get.orka.run | sudo bash
          orka3 --version

      - name: Log in to Orka
        env:
          ORKA_ENDPOINT_URL: ${{ secrets.ORKA_ENDPOINT }}
          ORKA_USER: ${{ secrets.ORKA_USER }}
          ORKA_PASSWORD: ${{ secrets.ORKA_PASSWORD }}
        run: |
          echo "$ORKA_PASSWORD" | orka3 login --endpoint "$ORKA_ENDPOINT_URL" --username "$ORKA_USER" --password-stdin

      - name: Run Ansible Playbook
        run: |
          source venv/bin/activate
          ansible-playbook orka_cicd.yml
          deactivate
