name: Orka CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install ansible requests
          deactivate

      - name: Install Orka CLI
        run: |
          brew tap macstadium/orka
          brew install orka3

      - name: Log in to Orka
        env:
          ORKA_ENDPOINT_URL: ${{ secrets.ORKA_ENDPOINT }}
        run: orka3 login

      - name: Run Ansible Playbook
        run: |
          source venv/bin/activate
          ansible-playbook manage_orka_vms.yml
          deactivate
